### ISSUE TITLE
Add capacity to ignore hidden/temporary files for target directory

### ISSUE THREAD

**Issue by sam5558** [doublemarket/grafana-rrd-server#43]
Hello,

Great project you have there. 
I ran into an issue, the target directory i'm using for grafana-rrd has some temporary hidden files (used by rsync). These hidden files creates some exceptions when trying to read/display data on my graphs on grafana, making me unable to use the simplejson plugin.

So, i think it could by great to have support for hidden files, so that we can specify whether we want to include all files in the target directory or ignore hidden files (.hiddenfile).

**Comment by doublemarket** [comment]
@sam5558 Hello, thank you for the comment here.

Since grafana-rrd-server only sees files containing ".rrd" in their file paths (ideally it should see only files with the ".rrd" extension, not ones containing the string), I don't think it can die with exceptions. Could you provide the messages you got and/or names of the hidden files?

**Comment by sam5558** [comment]
Hello,
Nevermind, i found a my way through this.
Thanks for your comment.
You can close the ticket.
