### ISSUE TITLE
Can't execute grafana-rrd-server

### ISSUE THREAD

**Issue by alexisc35** [doublemarket/grafana-rrd-server#44]
Hello,

I can't execute grafana-rrd-server command on my CentOS 7... 

I have :
"error while loading shared libraries: librrd.so.8: cannot open shared object file: No such file or directory"

I don't understand where this error can from. 

I have never learned or used GO language :/

Thank you

**Comment by MisterTwee** [comment]
I have encountered the same problem, the last version of grafana-rrd-server (currently v0.0.5?) needs a library librrd.so.8,  I have installed Stor2RRD in a Virtual Appliance running xorux (derived from Cent OS) which I cannot modify easily, but I found that on this Virtual Appliance librrd.so.4 (an older version of the rrd library)  is pre-installed AND  I found that a slightly older version of grafana-rrd-server also uses that same library  librrd.so.4.

1 + 1 = 2,  so installing this older version did the trick for me :
   v0.0.1
   @doublemarket doublemarket released this on Apr 2, 2017 · 17 commits to master since this release

   Assets
   2.14 MB grafana-rrd-server_linux_amd64.gz

Look under releases for version v0.0.1

Regards, Felix

**Comment by sam5558** [comment]
Here's a quick workaround that worked for me : 

Most likely you should have in your centos installation another librrd.so.* (librrd.so.4.2.0 for example) stored somewhere as a shared library, so : 
1/ search where your *.so library is
2/ create a symlink between librrd.so.* & librrd.so.8 (sudo ln -s librrd.so.4.2.0 librrd.so.8) 

Retry grafana-rrd-server. it should now work.
